#-------------------------------
# Site Settings
title: Liljen Ceramic Design
logo: '/images/logo.jpg'
author: Susann Winter
description: Contemporary Ceramic Artist


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Welcome'
      url: '/'
    - title: 'Artwork'
      url: '/blog/'
    - title: 'About the Artist'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Shipping Policy'
      url: '/elements/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Welcome to Liljen Ceramic Design! 
  hero__description: "Hello, I’m Susann, a ceramic artist and the creator behind Liljen Ceramic Design. <br>I create floral and coral-inspired wall installations alongside contemporary ceramic pieces. Some are functional, some are just here to look gorgeous. 
  Every piece is handmade with patience, love, and a touch of magic. Each one is unique, ensuring every collector owns something truly one of a kind. 
  Take a look around and bring a little art into your world! 
  
  <br><br>Love Susann from Liljen Ceramic Design"



#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Gallery 
  portfolio__gallery:
    - image: /images/product1.jpg
      title: Samantha Gades
      description: Brown photo frame beside wall <a href="https://unsplash.com/photos/8Od75hgzb9Y">Unsplash</a>

    - image: /images/gallery-02.jpg
      title: Paula Vermeulen
      description: Gray mountain covered by mountain <a href="https://unsplash.com/photos/_f2m3mEkaaU">Unsplash</a>

    - image: /images/product3.jpg
      title: Bench Accounting
      description: White wooden table near brown chair <a href="https://unsplash.com/photos/nvzvOPQW0gc">Unsplash</a>

    - image: /images/gallery-04.jpg
      title: Nord Wood
      description: White ceramic mug <a href="https://unsplash.com/photos/nDd3dIkkOLo">Unsplash</a>

    - image: /images/gallery-05.jpg
      title: Luca Bravo
      description: White ribs in a facade against a white sky <a href="https://unsplash.com/photos/alS7ewQ41M8">Unsplash</a>

    - image: /images/product4.jpg
      title: Isaac Benhesed
      description: Minimalist black coffee <a href="https://unsplash.com/photos/onLbXleIkds">Unsplash</a>

    - image: /images/product5.jpg
      title: Water Journal
      description: Water Journal is a bi-annual publication exploring the beauty and complexity of all things water <a href="https://unsplash.com/photos/EbuaKnSm8Zw">Unsplash</a>

    - image: /images/gallery-08.jpg
      title: Luca Bravo
      description: Worms eye view of city buildings <a href="https://unsplash.com/photos/a6x7YPiNxwI">Unsplash</a>

    - image: /images/product9.jpg
      title: Books and Laptop
      description: Silver laptop computer with two books on the top <a href="https://unsplash.com/photos/fFIAKABImf4">Unsplash</a>


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
#- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://www.facebook.com/Liljen.Ceramic.Design"}
#- {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
#- {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://www.instagram.com/liljenceramicdesign/"}
#- {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: 123
  # Add your email for contact form
  description: 123
#"Have questions? I’m here to help! <br><br>Feel free to reach out at hello@liljen.design - I love chatting about my work and helping you find the perfect piece.
#<br><br>Thank you for supporting handmade art—your love for unique ceramics keeps my passion alive!"
  
  # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id